import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/resources/styles/globals.css";
import ReactQueryProvider from "@/providers/react-query-provider";
import type { IChildren } from "@/resources/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: IChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <ReactQueryProvider>{children}</ReactQueryProvider>
    </body>
  </html>
);

export default RootLayout;